import { ExternalLink, PlayCircle } from 'lucide-react'
import type { SeriesDetails, WatchOption } from '../../../entities/movie/model'
import { mediaUrl } from '../../../shared/lib/mediaUrl'

const labels: Record<WatchOption['type'], string> = { stream: 'По подписке', free: 'Бесплатно', rent: 'Аренда', buy: 'Покупка' }

export function WatchOptions({ item }: { item: SeriesDetails }) {
  if (!item.watchOptions.length && !item.externalLinks.length) return null
  return (
    <section className="tech-panel rounded-3xl border border-white/8 bg-white/4 p-6 sm:p-8"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-300/12 text-emerald-300"><PlayCircle size={21} /></span><div><h2 className="text-xl font-black">Где посмотреть</h2><p className="text-sm text-slate-500">Проверь условия подписки и доступность на площадке</p></div></div>{item.watchOptions.length > 0 ? <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{item.watchOptions.map((option, index) => <a key={`${option.name}-${option.type}-${index}`} href={option.url} target="_blank" rel="noreferrer" className="tech-card flex items-center gap-3 rounded-2xl border border-white/8 bg-slate-950/50 p-3 transition hover:border-emerald-300/30 hover:bg-white/8">{option.logoUrl ? <img src={mediaUrl(option.logoUrl)} alt="" className="size-10 rounded-xl object-cover" /> : <span className="grid size-10 place-items-center rounded-xl bg-white/8"><PlayCircle size={18} /></span>}<div className="min-w-0"><p className="truncate text-sm font-bold">{option.name}</p><p className="mt-0.5 text-xs text-slate-500">{labels[option.type]}{option.region ? ` · ${option.region === 'BY' ? 'Беларусь' : 'Россия'}` : ''}</p></div><ExternalLink className="ml-auto shrink-0 text-slate-600" size={15} /></a>)}</div> : <p className="mt-5 text-sm text-slate-400">Ссылок на просмотр для России или Беларуси пока нет.</p>}<p className="mt-5 text-xs font-bold uppercase tracking-wider text-slate-500">Карточки в каталогах</p><div className="mt-2 flex flex-wrap gap-2">{item.externalLinks.map((link) => <a key={link.url} href={link.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-3 py-1.5 text-xs font-bold text-slate-300 hover:bg-white/8"><ExternalLink size={13} />{link.name}</a>)}</div>{item.sourceNames?.includes('TMDB') && item.watchOptions.length > 0 && <p className="mt-4 text-[11px] text-slate-600">Данные о площадках предоставлены JustWatch через TMDB. Наличие фильма может измениться.</p>}</section>
  )
}
